<a href="https://colab.research.google.com/github/wchunduri/DS_Project1/blob/main/Copy_of_Texas_EDA_June_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
# Code snippet 1
# Setting the dataset URL
url = 'https://raw.githubusercontent.com/nvamsimohan/DallasDSA/refs/heads/main/2023%20Texas%20High%20Schools%20Scores.csv'

# Display the url
url

'https://raw.githubusercontent.com/nvamsimohan/DallasDSA/refs/heads/main/2023%20Texas%20High%20Schools%20Scores.csv'

In [24]:
# Code snippet 2
# Importing pandas for data processing
import pandas

In [25]:
# Code snippet 3
# Importing the dataset from URL using pandas
data = pandas.read_csv(url)

# Display the data
data

,School,School URL,District,District URL,City,City URL,Zip,County,Phone,Is Title I,Is Charter,Is Magnet,Is Virtual,Number Students,Number Full-time Teachers,Student/Teacher Ratio,Percent Free/Disc Lunch,Percent Homes Rented,Percent of Unemployment,Percent Parents with Masters and above education,Percent parents with less than High School education,Percent Home Incomes with less than Median income,Home Prices Ranking,Community Health Ranking,Standard Score
0,Lasa High School,https://www.schooldigger.com/go/TX/schools/0894011930/school.aspx,Austin Independent School District,https://www.schooldigger.com/go/TX/district/08940/search.aspx,Austin,https://www.schooldigger.com/go/TX/city/Austin/search.aspx,78724,Travis County,(512) 414-2589,No,No,No,No,1254,75.7,16.5,14.0,2.6,0.1,23.2,23.6,0.1,6.9,43.6,97.2
1,School For The Talented And Gifted,https://www.schooldigger.com/go/TX/schools/1623005865/school.aspx,Dallas Independent School District,https://www.schooldigger.com/go/TX/district/16230/search.aspx,Dallas,https://www.schooldigger.com/go/TX/city/Dallas/search.aspx,75203,Dallas County,(972) 925-5970,Yes,No,Yes,No,464,26.5,17.5,32.5,8.8,0.4,15.5,41.2,0.2,2.8,31.0,96.9
2,School Of Science And Engineering,https://www.schooldigger.com/go/TX/schools/1623003641/school.aspx,Dallas Independent School District,https://www.schooldigger.com/go/TX/district/16230/search.aspx,Dallas,https://www.schooldigger.com/go/TX/city/Dallas/search.aspx,75203,Dallas County,(972) 925-5960,Yes,No,Yes,No,513,26.0,19.7,54.0,9.9,0.2,12.5,61.6,0.6,1.0,14.2,96.6
3,Health Careers High School,https://www.schooldigger.com/go/TX/schools/3312006023/school.aspx,Northside Independent School District,https://www.schooldigger.com/go/TX/district/33120/search.aspx,San Antonio,https://www.schooldigger.com/go/TX/city/San+Antonio/search.aspx,78229,Bexar County,(210) 397-5400,No,No,Yes,No,905,50.7,17.8,22.2,5.2,0.1,19.3,54.4,0.3,3.1,17.6,95.5
4,Debakey H S For Health Prof,https://www.schooldigger.com/go/TX/schools/2364002483/school.aspx,Houston Independent School District,https://www.schooldigger.com/go/TX/district/23640/search.aspx,Houston,https://www.schooldigger.com/go/TX/city/Houston/search.aspx,77030,Harris County,(713) 741-2410,Yes,No,Yes,No,939,50.9,18.4,42.9,16.8,0.5,30.0,37.1,0.4,2.0,13.1,95.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1816,W B Bizzell Academy,https://www.schooldigger.com/go/TX/schools/3219012965/school.aspx,Navasota Independent School District,https://www.schooldigger.com/go/TX/district/32190/search.aspx,Navasota,https://www.schooldigger.com/go/TX/city/Navasota/search.aspx,77868,Grimes County,(936) 825-4296,No,No,No,No,30,3.3,9.0,83.3,30.0,0.0,0.0,36.7,0.0,3.3,30.0,1.7
1817,Phoenix High School,https://www.schooldigger.com/go/TX/schools/1836008426/school.aspx,Elgin Independent School District,https://www.schooldigger.com/go/TX/district/18360/search.aspx,Elgin,https://www.schooldigger.com/go/TX/city/Elgin/search.aspx,78621,Bastrop County,(512) 281-9774,No,No,No,No,48,5.1,9.3,77.1,16.7,0.0,0.0,66.7,0.0,0.0,16.7,1.5
1818,Graduation Prep Academy Navarro,https://www.schooldigger.com/go/TX/schools/0894012824/school.aspx,Austin Independent School District,https://www.schooldigger.com/go/TX/district/08940/search.aspx,Austin,https://www.schooldigger.com/go/TX/city/Austin/search.aspx,78758,Travis County,(512) 414-2896,No,Yes,No,No,91,4.0,22.7,93.4,12.1,0.0,3.3,80.2,0.0,2.2,2.2,1.3
1819,Munday,https://www.schooldigger.com/go/TX/schools/0007113669/school.aspx,University Of Texas University Charter School,https://www.schooldigger.com/go/TX/district/00071/search.aspx,Austin,https://www.schooldigger.com/go/TX/city/Austin/search.aspx,78723,Travis County,(512) 997-8872,No,Yes,No,No,14,3.0,4.6,78.6,21.4,0.0,0.0,42.9,0.0,7.1,28.6,1.0
1820,La Feria Academy,https://www.schooldigger.com/go/TX/schools/2604006941/school.aspx,La Feria Independent School District,https://www.schooldigger.com/go/TX/district/26040/search.aspx,La Feria,https://www.schooldigger.com/go/TX/city/La+Feria/search.aspx,78559,Cameron County,(956) 797-8360,Yes,No,No,No,33,4.0,8.2,90.9,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.3

In [26]:
# Code snippet 4
# Displaying dataset columns
data.columns

Index(['School', 'School URL', 'District', 'District URL', 'City', 'City URL',
       'Zip', 'County', 'Phone', 'Is Title I', 'Is Charter', 'Is Magnet',
       'Is Virtual', 'Number Students', 'Number Full-time Teachers',
       'Student/Teacher Ratio', 'Percent Free/Disc Lunch',
       'Percent Homes Rented', 'Percent of Unemployment',
       'Percent Parents with Masters and above education',
       'Percent parents with less than High School education',
       'Percent Home Incomes with less than Median income',
       'Home Prices Ranking', 'Community Health Ranking', 'Standard Score'],
      dtype='object')

In [27]:
# Code snippet 5
# Displaying descriptive stats
data.describe()

,Zip,Number Students,Number Full-time Teachers,Student/Teacher Ratio,Percent Free/Disc Lunch,Percent Homes Rented,Percent of Unemployment,Percent Parents with Masters and above education,Percent parents with less than High School education,Percent Home Incomes with less than Median income,Home Prices Ranking,Community Health Ranking,Standard Score
count,1821.000000,1821.000000,1811.000000,1810.000000,1821.000000,1821.000000,1821.000000,1821.000000,1821.000000,1821.000000,1049.000000,804.000000,1821.000000
mean,77315.758375,916.175728,61.561016,13.560939,59.395936,10.565678,0.358210,2.416804,49.242394,0.107194,2.013632,25.547512,47.299890
std,1437.680272,992.964357,57.729077,4.968011,24.166854,13.997171,0.775274,6.184342,28.704876,0.464306,2.191142,25.982462,25.110679
min,75002.000000,0.000000,0.000000,0.300000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.300000
25%,76063.000000,205.000000,19.600000,10.300000,41.700000,1.000000,0.000000,0.000000,24.700000,0.000000,0.400000,2.800000,27.000000
50%,77358.000000,456.000000,36.200000,13.400000,60.000000,5.000000,0.200000,0.500000,45.000000,0.000000,1.500000,15.050000,48.500000
75%,78570.000000,1476.000000,96.350000,16.100000,79.400000,14.700000,0.500000,1.700000,74.200000,0.100000,3.000000,42.850000,67.700000
max,79938.000000,10450.000000,288.600000,80.000000,100.000000,97.300000,22.000000,84.600000,100.000000,15.700000,25.000000,93.700000,97.200000

In [28]:
# Code snippet 6
# Importing missingno package - to display the missing data proportion
import missingno as msno

In [29]:
# Code snippet 7
# Displaying the missing data proportion
msno.bar(data)

In [30]:
# Code snippet 8
# Dropping 'Home Prices Ranking', 'Community Health Ranking' columns due to missing data (more than 20%)
data80 = data.drop(['Home Prices Ranking', 'Community Health Ranking'], axis = 1)

# Displaying data80.columns
data80.columns

Index(['School', 'School URL', 'District', 'District URL', 'City', 'City URL',
       'Zip', 'County', 'Phone', 'Is Title I', 'Is Charter', 'Is Magnet',
       'Is Virtual', 'Number Students', 'Number Full-time Teachers',
       'Student/Teacher Ratio', 'Percent Free/Disc Lunch',
       'Percent Homes Rented', 'Percent of Unemployment',
       'Percent Parents with Masters and above education',
       'Percent parents with less than High School education',
       'Percent Home Incomes with less than Median income', 'Standard Score'],
      dtype='object')

In [31]:
# Code snippet 9
# Dropping NOISE variables - 'School', 'School URL',  'District URL',  'City URL','Phone'
predictors = data80.drop(['School', 'School URL',  'District URL',  'City URL','Phone'], axis = 1)

# Displaying predictors.columns
predictors.columns

Index(['District', 'City', 'Zip', 'County', 'Is Title I', 'Is Charter',
       'Is Magnet', 'Is Virtual', 'Number Students',
       'Number Full-time Teachers', 'Student/Teacher Ratio',
       'Percent Free/Disc Lunch', 'Percent Homes Rented',
       'Percent of Unemployment',
       'Percent Parents with Masters and above education',
       'Percent parents with less than High School education',
       'Percent Home Incomes with less than Median income', 'Standard Score'],
      dtype='object')

In [32]:
# Code snippet 10
# Converting Zip to a string variable
predictors['Zip'] = predictors['Zip'].astype(str)

In [33]:
# Code snippet 11
# Installing fg-data-profiling package for detailed descriptive and Exploratory Data Analysis
!pip install fg-data-profiling

Requirement already satisfied: fg-data-profiling in /usr/local/lib/python3.12/dist-packages (4.19.1)
Requirement already satisfied: scipy<1.17,>=1.8 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (2.12.3)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in /usr/local/lib/python3.12/dist-packages (from visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (2.0.2)
Requirement already satisfied: minify-html>=0.15.0 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (4.5.2)
Requirement already satisfied: imagehash==4.3.2 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->fg-data-profiling) (1.9.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->fg-data-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=3.1.6->fg-data-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (26.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba<0.63,>=0.60->fg-data-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->fg-data-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->fg-data-profiling) (2026.2)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.12/dist-packages (from phik<0.13,>=0.12.5->fg-data-profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->fg-data-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->fg-data-profiling) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->fg-data-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->fg-data-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->fg-data-profiling) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->fg-data-profiling) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->fg-data-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->fg-data-profiling) (2026.5.20)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels<1,>=0.13.2->fg-data-profiling) (1.0.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (3.6.1)
Requirement already satisfied: puremagic in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (2.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->fg-data-profiling) (1.17.0)

In [34]:
# Code snippet 12
# Importing data_profiling function from the fg-data-profiling package
import data_profiling

In [13]:
# Code snippet 13
# Generating detailed data profiling report using the data_profiling function
profile  = data_profiling.ProfileReport(predictors, title = 'TX Schools Data Profiling Report')

# Converting raw profile report into an interactive HTML report
profile.to_file('TX Schools Data Profiling Report.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/18 [00:00<?, ?it/s]
  6%|▌         | 1/18 [00:00<00:02,  8.20it/s]
 22%|██▏       | 4/18 [00:00<00:01,  8.90it/s]
 50%|█████     | 9/18 [00:00<00:00, 18.40it/s]
100%|██████████| 18/18 [00:00<00:00, 24.86it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [14]:
min_students = predictors['Number Students'].min()
max_students = predictors['Number Students'].max()

print(f"Minimum Number of Students: {min_students}")
print(f"Maximum Number of Students: {max_students}")

Minimum Number of Students: 0
Maximum Number of Students: 10450

In [15]:
districts_high_free_lunch = predictors[predictors['Percent Free/Disc Lunch'] > 25]['District'].unique()

print("Districts where 'Percent Free/Disc Lunch' exceeds 25%:")
for district in districts_high_free_lunch:
    print(district)

Districts where 'Percent Free/Disc Lunch' exceeds 25%:
Dallas Independent School District
Houston Independent School District
Grand Prairie Independent School District
Tyler Independent School District
Ut Tyler University Academy
Laredo Independent School District
Klondike Independent School District
Lubbock Independent School District
Alief Independent School District
Cedar Hill Independent School District
El Paso Independent School District
Judson Independent School District
Gruver Independent School District
McAllen Independent School District
Sands Consolidated Independent School District
Panola Charter School
Glasscock County Independent School District
Bastrop Independent School District
South Texas Independent School District
Cypress-Fairbanks Independent School District
Houston Gateway Academy Inc
Fayetteville Independent School District
Flatonia Independent School District
Jayton-Girard Independent School District
Texas College Preparatory Academies
Newcastle Independent School District
Borden County Independent School District
Midland Independent School District
Somerset Independent School District
Happy Independent School District
Shiner Independent School District
Paint Creek Independent School District
Lindale Independent School District
Clear Creek Independent School District
Goldthwaite Independent School District
Killeen Independent School District
Waxahachie Independent School District
Kelton Independent School District
Comstock Independent School District
Abilene Independent School District
Mason Independent School District
Arlington Independent School District
Bryson Independent School District
Cisco Independent School District
Austin Independent School District
Poth Independent School District
Ropes Independent School District
Hartley Independent School District
Saint Jo Independent School District
New Braunfels Independent School District
Brownsville Independent School District
Ysleta Independent School District
Katy Independent School District
Pearland Independent School District
Harmony School Of Science - Houston
Idea Public Schools
Harlingen Consolidated Independent School District
Mumford Independent School District
Iredell Independent School District
Paradise Independent School District
Lamar Consolidated Independent School District
Lovelady Independent School District
Alpine Independent School District
McKinney Independent School District
Union Grove Independent School District
Round Rock Independent School District
Miles Independent School District
Knippa Independent School District
Caddo Mills Independent School District
Tioga Independent School District
College Station Independent School District
Canadian Independent School District
Iola Independent School District
Canton Independent School District
Bryan Independent School District
Whitharral Independent School District
Grandview Independent School District
Santo Independent School District
Eula Independent School District
Munday Consolidated Independent School District
Silverton Independent School District
Socorro Independent School District
Shallowater Independent School District
Nueces Canyon Consolidated Independent School District
Martins Mill Independent School District
North Zulch Independent School District
Goose Creek Consolidated Independent School District
Round Top-Carmine Independent School District
Clint Independent School District
Franklin Independent School District
Canutillo Independent School District
Taylor Independent School District
Spearman Independent School District
McLean Independent School District
Centerville Independent School District
Plano Independent School District
Midway Independent School District
Bullard Independent School District
New Caney Independent School District
Corpus Christi Independent School District
Carrollton-Farmers Branch Independent School District
Wylie Independent School District
Iowa Park Consolidated Independent School District
Industrial Independent School District
Tomball Independent School District
Whitehouse Independent School District
Avery Independent School District
Redwater Independent School District
Brookeland Independent School District
McLeod Independent School District
Neches Independent School District
Humble Independent School District
Grapevine-Colleyville Independent School District
Turkey-Quitaque Independent School District
Galena Park Independent School District
Giddings Independent School District
Troup Independent School District
Hallsville Independent School District
Prairie Valley Independent School District
Irion County Independent School District
East Bernard Independent School District
Johnson City Independent School District
Seymour Independent School District
Wellman-Union Consolidated Independent School District
Fort Bend Independent School District
Utopia Independent School District
Whitewright Independent School District
Lubbock-Cooper Independent School District
Leon Independent School District
Bosqueville Independent School District
Era Independent School District
San Antonio Independent School District
Hardin-Jefferson Independent School District
Albany Independent School District
Milano Independent School District
Cayuga Independent School District
Sidney Independent School District
Dublin Independent School District
Spring Hill Independent School District
Bremond Independent School District
Spring Branch Independent School District
Tolar Independent School District
Northside Independent School District
Chillicothe Independent School District
Robert Lee Independent School District
Slocum Independent School District
Sharyland Independent School District
Fort Elliott Consolidated Independent School District
Hedley Independent School District
Klein Independent School District
Ector County Independent School District
Hudson Independent School District
Ingram Independent School District
Christoval Independent School District
Arp Independent School District
Water Valley Independent School District
Mansfield Independent School District
Central Heights Independent School District
Leveretts Chapel Independent School District
Teague Independent School District
Navarro Independent School District
Olney Independent School District
Onalaska Independent School District
Alvin Independent School District
Sundown Independent School District
Hamilton Independent School District
Lumberton Independent School District
Huntsville Independent School District
Glen Rose Independent School District
Pasadena Independent School District
Amarillo Independent School District
Peaster Independent School District
Trenton Independent School District
Anderson-Shiro Consolidated Independent School District
Palmer Independent School District
Keller Independent School District
Priority Charter Schools
Early Independent School District
Highland Park Independent School District
Bells Independent School District
Elkhart Independent School District
Winnsboro Independent School District
Aldine Independent School District
Comal Independent School District
Ume Preparatory Academy
Electra Independent School District
Wolfe City Independent School District
Follett Independent School District
Latexo Independent School District
Callisburg Independent School District
Magnolia Independent School District
Burton Independent School District
Birdville Independent School District
Deer Park Independent School District
Terrell County Independent School District
Weimar Independent School District
Henrietta Independent School District
White Oak Independent School District
Sonora Independent School District
Blum Independent School District
Frenship Independent School District
Premier High Schools
Cross Roads Independent School District
Westbrook Independent School District
Sabine Independent School District
Woden Independent School District
Sterling City Independent School District
Northwest Independent School District
Bangs Independent School District
Archer City Independent School District
Rochelle Independent School District
Post Independent School District
Pharr-San Juan-Alamo Independent School District
Pflugerville Independent School District
Valley Mills Independent School District
Windthorst Independent School District
Lingleville Independent School District
Claude Independent School District
Clyde Consolidated Independent School District
Spring Independent School District
Hooks Independent School District
Tatum Independent School District
Savoy Independent School District
Troy Independent School District
Miller Grove Independent School District
High Point Academy
Ingleside Independent School District
Clarendon Independent School District
Conroe Independent School District
Harmony Science Academy (Waco)
Mount Pleasant Independent School District
Wellington Independent School District
Shelbyville Independent School District
Mineola Independent School District
Howe Independent School District
Forsan Independent School District
Hallettsville Independent School District
Douglass Independent School District
Rogers Independent School District
Fort Worth Independent School District
Beckville Independent School District
Calallen Independent School District
Benjamin Independent School District
Hico Independent School District
Abbott Independent School District
Chisum Independent School District
Nederland Independent School District
Sudan Independent School District
West Independent School District
Carthage Independent School District
Thorndale Independent School District
Cross Plains Independent School District
Eagle Mt-Saginaw Independent School District
Booker Independent School District
Madisonville Consolidated Independent School District
Pineywoods Community Academy
Wheeler Independent School District
Harleton Independent School District
Hughes Springs Independent School District
Yes Prep Public Schools Inc
La Joya Independent School District
Henry Ford Academy Alameda School For Art + Design
Kerrville Independent School District
Schleicher Independent School District
Panther Creek Consolidated Independent School District
Bronte Independent School District
Needville Independent School District
Shamrock Independent School District
Jourdanton Independent School District
Petersburg Independent School District
Hardin Independent School District
Crane Independent School District
Whitesboro Independent School District
Dodd City Independent School District
Elysian Fields Independent School District
Cushing Independent School District
Quanah Independent School District
Mullin Independent School District
Gilmer Independent School District
Marion Independent School District
Oglesby Independent School District
Decatur Independent School District
Miami Independent School District
Groveton Independent School District
Blanco Independent School District
Harper Independent School District
Orangefield Independent School District
Hays Consolidated Independent School District
Anna Independent School District
Harmony School Of Excellence
North Lamar Independent School District
Flour Bluff Independent School District
Harmony Independent School District
Gholson Independent School District
Channing Independent School District
Stephenville Independent School District
Odem-Edroy Independent School District
Frankston Independent School District
May Independent School District
Detroit Independent School District
George West Independent School District
Aquilla Independent School District
Ponder Independent School District
Zephyr Independent School District
Waskom Independent School District
Junction Independent School District
Harlandale Independent School District
Beaumont Independent School District
Veribest Independent School District
Orange Grove Independent School District
Roby Consolidated Independent School District
Sabine Pass Independent School District
Graham Independent School District
Richardson Independent School District
Denison Independent School District
North East Independent School District
D'Hanis Independent School District
Wichita Falls Independent School District
New Diana Independent School District
Lipan Independent School District
East Texas Charter Schools
Midlothian Independent School District
Santa Gertrudis Independent School District
Llano Independent School District
Stamford Independent School District
Medina Valley Independent School District
Motley County Independent School District
Forestburg Independent School District
Jacksboro Independent School District
Moulton Independent School District
Zavalla Independent School District
San Felipe-Del Rio Consolidated Independent School District
Anahuac Independent School District
Clifton Independent School District
Nyos Charter School
Tidehaven Independent School District
Bridge City Independent School District
Dumas Independent School District
Alvord Independent School District
Slidell Independent School District
Gustine Independent School District
New Summerfield Independent School District
De Leon Independent School District
Rivercrest Independent School District
Rotan Independent School District
Kirbyville Consolidated Independent School District
Childress Independent School District
Holland Independent School District
Buna Independent School District
Lampasas Independent School District
Fredericksburg Independent School District
Bland Independent School District
Mount Enterprise Independent School District
Princeton Independent School District
Simms Independent School District
New Frontiers Public Schools Inc
Coleman Independent School District
Harmony Science Academy (Austin)
Spur Independent School District
Cranfills Gap Independent School District
Brazos Independent School District
Rice Independent School District
Normangee Independent School District
Scurry-Rosser Independent School District
Keene Independent School District
Cooper Independent School District
San Saba Independent School District
Chireno Independent School District
Schulenburg Independent School District
Richland Springs Independent School District
Pittsburg Independent School District
Paris Independent School District
Buffalo Independent School District
Jean Massieu Academy
Trinidad Independent School District
Axtell Independent School District
Lapoynor Independent School District
New Deal Independent School District
Milford Independent School District
Stanton Independent School District
Pottsboro Independent School District
School Of Science And Technology
Poolville Independent School District
Santa Anna Independent School District
East Chambers Independent School District
Blanket Independent School District
Laneville Independent School District
Farmersville Independent School District
Boles Independent School District
Honey Grove Independent School District
Alvarado Independent School District
Garland Independent School District
Como-Pickton Consolidated Independent School District
Pettus Independent School District
Sunray Independent School District
Sanger Independent School District
KIPP Texas Public Schools
Edgewood Independent School District
Chapel Hill Independent School District
Brady Independent School District
Avalon Independent School District
Cherokee Independent School District
Perrin-Whitt Consolidated Independent School District
Roscoe Collegiate Independent School District
Aspermont Independent School District
Smyer Independent School District
Louise Independent School District
Joaquin Independent School District
Caldwell Independent School District
Friona Independent School District
Port Neches-Groves Independent School District
Linden-Kildare Consolidated Independent School District
Patton Springs Independent School District
Haskell Consolidated Independent School District
Harmony Science Academy (El Paso)
Sulphur Springs Independent School District
Greenwood Independent School District
White Deer Independent School District
Newman International Academy Of Arlington
Pleasanton Independent School District
Hondo Independent School District
Burleson Independent School District
Loraine Independent School District
San Perlita Independent School District
Mildred Independent School District
Joshua Independent School District
Wink-Loving Independent School District
Springlake-Earth Independent School District
Sulphur Bluff Independent School District
Saltillo Independent School District
Brownsboro Independent School District
Plainview Independent School District
Quitman Independent School District
Denton Independent School District
Longview Independent School District
Italy Independent School District
Priddy Independent School District
Stratford Independent School District
Lewisville Independent School District
Palacios Independent School District
Hutto Independent School District
Texas Leadership Public Schools
Bellevue Independent School District
Malakoff Independent School District
Prairiland Independent School District
International Leadership Of Texas (Iltexas)
Fairfield Independent School District
Hillsboro Independent School District
Comfort Independent School District
Celeste Independent School District
Fruitvale Independent School District
Rio Vista Independent School District
Abernathy Independent School District
Ganado Independent School District
Lake Dallas Independent School District
Brownwood Independent School District
Huntington Independent School District
Perryton Independent School District
Apple Springs Independent School District
Tuloso-Midway Independent School District
Robinson Independent School District
Sanford-Fritch Independent School District
Ore City Independent School District
Ft Hancock Independent School District
Blackwell Consolidated Independent School District
Maud Independent School District
Bellville Independent School District
Universal Academy
Eustace Independent School District
Ballinger Independent School District
Plains Independent School District
West Rusk County Consolidated Independent School District
Granbury Independent School District
Sweeny Independent School District
Comanche Independent School District
Southland Independent School District
Weatherford Independent School District
Devine Independent School District
Austwell-Tivoli Independent School District
Huffman Independent School District
Nixon-Smiley Consolidated Independent School District
Weslaco Independent School District
Lufkin Independent School District
Colorado Independent School District
Roosevelt Independent School District
Queen City Independent School District
Woodson Independent School District
Skidmore-Tynan Independent School District
Boling Independent School District
Cuero Independent School District
Cotton Center Independent School District
Boyd Independent School District
Uplift Education
Stockdale Independent School District
Rising Star Independent School District
Marathon Independent School District
Corrigan-Camden Independent School District
Texline Independent School District
Rusk Independent School District
Buena Vista Independent School District
City View Independent School District
Sealy Independent School District
Menard Independent School District
Krum Independent School District
Muleshoe Independent School District
Azle Independent School District
Gary Independent School District
Borger Independent School District
Vanguard Academy
Mission Consolidated Independent School District
Red Oak Independent School District
Garrison Independent School District
Nocona Independent School District
Springtown Independent School District
Levelland Independent School District
Kopperl Independent School District
Center Point Independent School District
Hubbard Independent School District
Medina Independent School District
La Grange Independent School District
Baird Independent School District
Gatesville Independent School District
Van Independent School District
S And S Consolidated Independent School District
Balmorhea Independent School District
Bluff Dale Independent School District
Chilton Independent School District
Big Sandy Independent School District
North Hopkins Independent School District
Denver City Independent School District

In [16]:
num_districts = len(districts_high_free_lunch)
print(f"Number of districts where 'Percent Free/Disc Lunch' exceeds 25%: {num_districts}")

Number of districts where 'Percent Free/Disc Lunch' exceeds 25%: 992

In [17]:
median_free_lunch = predictors['Percent Free/Disc Lunch'].median()
print(f"The median percentage of students receiving free or discounted lunches is: {median_free_lunch}%")

The median percentage of students receiving free or discounted lunches is: 60.0%

In [18]:
print('Percentage of schools by type:')
for col in ['Is Title I', 'Is Charter', 'Is Magnet', 'Is Virtual']:
    # Convert 'Yes'/'No' to 1/0 for calculation
    predictors[col] = predictors[col].map({'Yes': 1, 'No': 0})
    percentage = predictors[col].mean() * 100
    print(f'- {col}: {percentage:.2f}%')

Percentage of schools by type:
- Is Title I: 60.52%
- Is Charter: 16.58%
- Is Magnet: 4.28%
- Is Virtual: 0.33%

In [19]:
# code snippet 14
#installing autoviz
!pip install autoviz

Collecting autoviz
  Downloading autoviz-0.1.905-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: xlrd in /usr/local/lib/python3.12/dist-packages (from autoviz) (2.0.2)
Requirement already satisfied: wordcloud in /usr/local/lib/python3.12/dist-packages (from autoviz) (1.9.6)
Collecting emoji (from autoviz)
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Collecting pyamg (from autoviz)
  Downloading pyamg-5.3.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.1 kB)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from autoviz) (1.6.1)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.12/dist-packages (from autoviz) (0.14.6)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from autoviz) (3.9.1)
Requirement already satisfied: textblob in /usr/local/lib/python3.12/dist-packages (from autoviz) (0.19.0)
Collecting xgboost<1.7,>=0.82 (from autoviz)
  Downloading xgboost-1.6.2-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
Requirement already satisfied: fsspec>=0.8.3 in /usr/local/lib/python3.12/dist-packages (from autoviz) (2025.3.0)
Requirement already satisfied: typing-extensions>=4.1.1 in /usr/local/lib/python3.12/dist-packages (from autoviz) (4.15.0)
Collecting pandas-dq>=1.29 (from autoviz)
  Downloading pandas_dq-1.29-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.24.0 in /usr/local/lib/python3.12/dist-packages (from autoviz) (2.0.2)
Collecting hvplot>=0.9.2 (from autoviz)
  Downloading hvplot-0.12.2-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: holoviews>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from autoviz) (1.22.1)
Requirement already satisfied: panel>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from autoviz) (1.9.3)
Requirement already satisfied: pandas>=2.0 in /usr/local/lib/python3.12/dist-packages (from autoviz) (2.2.2)
Requirement already satisfied: matplotlib>3.7.4 in /usr/local/lib/python3.12/dist-packages (from autoviz) (3.10.0)
Requirement already satisfied: seaborn>0.12.2 in /usr/local/lib/python3.12/dist-packages (from autoviz) (0.13.2)
Requirement already satisfied: bokeh>=3.1 in /usr/local/lib/python3.12/dist-packages (from holoviews>=1.16.0->autoviz) (3.8.2)
Requirement already satisfied: colorcet in /usr/local/lib/python3.12/dist-packages (from holoviews>=1.16.0->autoviz) (3.2.1)
Requirement already satisfied: narwhals>=2 in /usr/local/lib/python3.12/dist-packages (from holoviews>=1.16.0->autoviz) (2.22.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from holoviews>=1.16.0->autoviz) (26.2)
Requirement already satisfied: param<3.0,>=2.0 in /usr/local/lib/python3.12/dist-packages (from holoviews>=1.16.0->autoviz) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from holoviews>=1.16.0->autoviz) (2.9.0.post0)
Requirement already satisfied: pyviz-comms>=2.1 in /usr/local/lib/python3.12/dist-packages (from holoviews>=1.16.0->autoviz) (3.0.6)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>3.7.4->autoviz) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>3.7.4->autoviz) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>3.7.4->autoviz) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>3.7.4->autoviz) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>3.7.4->autoviz) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>3.7.4->autoviz) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->autoviz) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->autoviz) (2026.2)
Requirement already satisfied: linkify-it-py in /usr/local/lib/python3.12/dist-packages (from panel>=1.4.0->autoviz) (2.1.0)
Requirement already satisfied: markdown in /usr/local/lib/python3.12/dist-packages (from panel>=1.4.0->autoviz) (3.10.2)
Requirement already satisfied: markdown-it-py in /usr/local/lib/python3.12/dist-packages (from panel>=1.4.0->autoviz) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.12/dist-packages (from panel>=1.4.0->autoviz) (0.6.1)
Requirement already satisfied: nh3 in /usr/local/lib/python3.12/dist-packages (from panel>=1.4.0->autoviz) (0.3.5)
Requirement already satisfied: panel-material-ui>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from panel>=1.4.0->autoviz) (0.12.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from panel>=1.4.0->autoviz) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from panel>=1.4.0->autoviz) (4.67.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->autoviz) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->autoviz) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->autoviz) (3.6.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->autoviz) (8.4.1)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk->autoviz) (2025.11.3)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels->autoviz) (1.0.2)
Requirement already satisfied: Jinja2>=2.9 in /usr/local/lib/python3.12/dist-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (3.1.6)
Requirement already satisfied: PyYAML>=3.10 in /usr/local/lib/python3.12/dist-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (6.0.3)
Requirement already satisfied: tornado>=6.2 in /usr/local/lib/python3.12/dist-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (6.5.7)
Requirement already satisfied: xyzservices>=2021.09.1 in /usr/local/lib/python3.12/dist-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (2026.3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->holoviews>=1.16.0->autoviz) (1.17.0)
Requirement already satisfied: uc-micro-py in /usr/local/lib/python3.12/dist-packages (from linkify-it-py->panel>=1.4.0->autoviz) (2.0.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py->panel>=1.4.0->autoviz) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->panel>=1.4.0->autoviz) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->panel>=1.4.0->autoviz) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->panel>=1.4.0->autoviz) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->panel>=1.4.0->autoviz) (2026.5.20)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from Jinja2>=2.9->bokeh>=3.1->holoviews>=1.16.0->autoviz) (3.0.3)
Downloading autoviz-0.1.905-py3-none-any.whl (67 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.5/67.5 kB 2.8 MB/s eta 0:00:00
Downloading hvplot-0.12.2-py3-none-any.whl (180 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 180.6/180.6 kB 8.3 MB/s eta 0:00:00
Downloading pandas_dq-1.29-py3-none-any.whl (29 kB)
Downloading xgboost-1.6.2-py3-none-manylinux2014_x86_64.whl (255.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 255.9/255.9 MB 5.0 MB/s eta 0:00:00
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 29.2 MB/s eta 0:00:00
Downloading pyamg-5.3.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 58.1 MB/s eta 0:00:00
Installing collected packages: emoji, xgboost, pyamg, pandas-dq, hvplot, autoviz
  Attempting uninstall: xgboost
    Found existing installation: xgboost 3.2.0
    Uninstalling xgboost-3.2.0:
      Successfully uninstalled xgboost-3.2.0
Successfully installed autoviz-0.1.905 emoji-2.15.0 hvplot-0.12.2 pandas-dq-1.29 pyamg-5.3.0 xgboost-1.6.2

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [20]:
#code snippet 15
#importing autoviz componenets
from autoviz.AutoViz_Class import AutoViz_Class

Imported v0.1.905. Please call AutoViz in this sequence:
    AV = AutoViz_Class()
    %matplotlib inline
    dfte = AV.AutoViz(filename, sep=',', depVar='', dfte=None, header=0, verbose=1, lowess=False,
               chart_format='svg',max_rows_analyzed=150000,max_cols_analyzed=30, save_plot_dir=None)

In [21]:
#code snippet 16
#starting/instantiating autoviz
AV = AutoViz_Class()

In [22]:
#code snippet 17
#generating visuals using autoviz
AV.AutoViz(predictors, depVar='Standard Score', verbose=2)

Shape of your Data Set loaded: (1821, 18)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...
  Printing up to 30 columns (max) in each category:
    Numeric Columns : ['Number Full-time Teachers', 'Student/Teacher Ratio', 'Percent Free/Disc Lunch', 'Percent Homes Rented', 'Percent of Unemployment', 'Percent Parents with Masters and above education', 'Percent parents with less than High School education', 'Percent Home Incomes with less than Median income']
    Integer-Categorical Columns: ['Number Students']
    String-Categorical Columns: []
    Factor-Categorical Columns: []
    String-Boolean Columns: []
    Numeric-Boolean Columns: ['Is Title I', 'Is Charter', 'Is Magnet', 'Is Virtual']
    Discrete String Columns: ['City', 'County']
    NLP text Columns: ['District', 'Zip']
    Date Time Columns: []
    ID Columns: []
    Columns that will not be considered in modeling: []
    17 Predictors classified...
        No variables removed since no ID or low-information variables found in data set

################ Regression problem #####################
   Columns to delete:
'   []'
   Boolean variables %s
"   ['Is Title I', 'Is Charter', 'Is Magnet', 'Is Virtual']"
   Categorical variables %s
"   ['Number Students', 'Is Title I', 'Is Charter', 'Is Magnet', 'Is Virtual']"
   Continuous variables %s
("   ['Number Full-time Teachers', 'Student/Teacher Ratio', 'Percent Free/Disc "
 "Lunch', 'Percent Homes Rented', 'Percent of Unemployment', 'Percent Parents "
 "with Masters and above education', 'Percent parents with less than High "
 "School education', 'Percent Home Incomes with less than Median income']")
   Discrete string variables %s
"   ['District', 'Zip', 'City', 'County']"
   Date and time variables %s
'   []'
   ID variables %s
'   []'
   Target variable %s
'   Standard Score'
To fix these data quality issues in the dataset, import FixDQ from autoviz...
    All variables classified into correct types.

Number of All Scatter Plots = 36

[nltk_data] Downloading collection 'popular'
[nltk_data]    |
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cmudict.zip.
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gazetteers.zip.
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/genesis.zip.
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gutenberg.zip.
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/inaugural.zip.
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/movie_reviews.zip.
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/names.zip.
[nltk_data]    | Downloading package shakespeare to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/shakespeare.zip.
[nltk_data]    | Downloading package stopwords to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/stopwords.zip.
[nltk_data]    | Downloading package treebank to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/treebank.zip.
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/twitter_samples.zip.
[nltk_data]    | Downloading package omw to /root/nltk_data...
[nltk_data]    | Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]    | Downloading package wordnet to /root/nltk_data...
[nltk_data]    | Downloading package wordnet2021 to /root/nltk_data...
[nltk_data]    | Downloading package wordnet31 to /root/nltk_data...
[nltk_data]    | Downloading package wordnet_ic to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/wordnet_ic.zip.
[nltk_data]    | Downloading package words to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/words.zip.
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping chunkers/maxent_ne_chunker.zip.
[nltk_data]    | Downloading package punkt to /root/nltk_data...
[nltk_data]    |   Unzipping tokenizers/punkt.zip.
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...

Could not draw wordcloud plot for District.
Looks like you are missing some required data for this feature.

To download the necessary data, simply run

    python -m textblob.download_corpora

or use the NLTK downloader to download the missing data: http://nltk.org/data.html
If this doesn't fix the problem, file an issue at https://github.com/sloria/TextBlob/issues.

Could not draw wordcloud plot for Zip.
Looks like you are missing some required data for this feature.

To download the necessary data, simply run

    python -m textblob.download_corpora

or use the NLTK downloader to download the missing data: http://nltk.org/data.html
If this doesn't fix the problem, file an issue at https://github.com/sloria/TextBlob/issues.

Could not draw wordcloud plot for City.
Looks like you are missing some required data for this feature.

To download the necessary data, simply run

    python -m textblob.download_corpora

or use the NLTK downloader to download the missing data: http://nltk.org/data.html
If this doesn't fix the problem, file an issue at https://github.com/sloria/TextBlob/issues.

Could not draw wordcloud plot for County.
Looks like you are missing some required data for this feature.

To download the necessary data, simply run

    python -m textblob.download_corpora

or use the NLTK downloader to download the missing data: http://nltk.org/data.html
If this doesn't fix the problem, file an issue at https://github.com/sloria/TextBlob/issues.

All Plots are saved in ./AutoViz_Plots/Standard Score
Time to run AutoViz = 37 seconds

[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    |
[nltk_data]  Done downloading collection popular

,District,City,Zip,County,Is Title I,Is Charter,Is Magnet,Is Virtual,Number Students,Number Full-time Teachers,Student/Teacher Ratio,Percent Free/Disc Lunch,Percent Homes Rented,Percent of Unemployment,Percent Parents with Masters and above education,Percent parents with less than High School education,Percent Home Incomes with less than Median income,Standard Score
0,Austin Independent School District,Austin,78724,Travis County,0,0,0,0,1254,75.7,16.5,14.0,2.6,0.1,23.2,23.6,0.1,97.2
1,Dallas Independent School District,Dallas,75203,Dallas County,1,0,1,0,464,26.5,17.5,32.5,8.8,0.4,15.5,41.2,0.2,96.9
2,Dallas Independent School District,Dallas,75203,Dallas County,1,0,1,0,513,26.0,19.7,54.0,9.9,0.2,12.5,61.6,0.6,96.6
3,Northside Independent School District,San Antonio,78229,Bexar County,0,0,1,0,905,50.7,17.8,22.2,5.2,0.1,19.3,54.4,0.3,95.5
4,Houston Independent School District,Houston,77030,Harris County,1,0,1,0,939,50.9,18.4,42.9,16.8,0.5,30.0,37.1,0.4,95.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1816,Navasota Independent School District,Navasota,77868,Grimes County,0,0,0,0,30,3.3,9.0,83.3,30.0,0.0,0.0,36.7,0.0,1.7
1817,Elgin Independent School District,Elgin,78621,Bastrop County,0,0,0,0,48,5.1,9.3,77.1,16.7,0.0,0.0,66.7,0.0,1.5
1818,Austin Independent School District,Austin,78758,Travis County,0,1,0,0,91,4.0,22.7,93.4,12.1,0.0,3.3,80.2,0.0,1.3
1819,University Of Texas University Charter School,Austin,78723,Travis County,0,1,0,0,14,3.0,4.6,78.6,21.4,0.0,0.0,42.9,0.0,1.0
1820,La Feria Independent School District,La Feria,78559,Cameron County,1,0,0,0,33,4.0,8.2,90.9,0.0,0.0,0.0,100.0,0.0,0.3